local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
mirror:
  service: Mirror
  primary: storj
  mirrors: [solar_communications]
solar_communications:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:solar_communications, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:solar_communications, :secret_access_key) %>
  endpoint: https://s3.solarcom.ch
  bucket: smart_contract_hub-<%= Rails.env %>
storj:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:storj, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:storj, :secret_access_key) %>
  region: global
  endpoint: https://gateway.storjshare.io
  bucket: smart-contract-hub-<%= Rails.env %>
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
